"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['quackhunt.py']
DATA_FILES = [
    ('img',
             ['./img/crosshair.png',
              './img/may1.png',
              './img/bg.jpg']
     ),
    ('sfx',
              ['./sfx/ambience.ogg',
              './sfx/gunshot.ogg',
              './sfx/chicken.ogg',
              './sfx/duck_startle.ogg']
     ),
    ('music',
              ['./music/mozart.ogg']
     )
    ]
OPTIONS = {'argv_emulation': False, 'iconfile': 'duck.icns',
           'excludes': ['OpenGL', 'numpy']
           }

setup(
    name='Quackhunt',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
